name: Commitlint

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    name: Lint Commit Messages
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@f133a0d95090ef2609192b4a21f54e20af819ea9 # v6
        with:
          configFile: .commitlintrc.yml
